#[macro_export]
macro_rules! tr {
    ($content:expr) => {
        r18::translate("", $content)
    };
    ($content:expr, $($arg:expr),+) => {{
        use r18::{Format, SimpleCurlyFormat};
        SimpleCurlyFormat.format(r18::translate("", $content), &[$($arg),+])
            .unwrap_or_default()
    }};
    ([$prefix:expr] $content:expr) => {
        r18::translate($prefix, $content)
    };
    ([$prefix:expr] $content:expr, $($arg:expr),+) => {{
        use r18::{Format, SimpleCurlyFormat};
        SimpleCurlyFormat.format(r18::translate($prefix, $content), &[$($arg),+])
            .unwrap_or_default()
    }};
}

#[macro_export]
macro_rules! set_locale {
    ($locale:expr) => {
        // this function is generated by r18::init
        crate::set_locale($locale)
    };
}

#[macro_export]
macro_rules! locale {
    () => {
        // this function is generated by r18::init
        crate::locale()
    };
}
